language: node_js

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t bitcoinregret .
      - docker tag bitcoinregret $DOCKER_USERNAME/bitcoinregret:latest
      - docker push $DOCKER_USERNAME/bitcoinregret:latest