const largeNumbers = {
  1: "One",
  2: "Ten",
  3: "Hundred",
  4: "Thousand",
  5: "Ten Thousand",
  6: "Million",
  9: "Billion",
  12: "Trillion",
  15: "Quadrillion",
  18: "Quintillion",
  21: "Sextillion",
  24: "Septillion",
  27: "Octillion",
  30: "Nonillion",
  33: "Decillion",
  36: "Undecillion",
  39: "Duodecillion",
  42: "Tredecillion",
  45: "Quattuordecillion",
  48: "Quindecillion",
  51: "Sexdecillion",
  54: "Septendecillion",
  57: "Octodecillion",
  60: "Novemdecillion",
  63: "Vigintillion",
  66: "Unvigintillion",
  69: "Duovigintillion",
  72: "Trevigintillion",
  75: "Quattuorvigintillio",
  78: "Quinvigintillion",
  81: "Sexvigintillion",
  84: "Septenvigintillion",
  87: "Octovigintillion",
  90: "Novemvigintillion",
  93: "Trigintillion",
  96: "Untrigintillion",
  99: "Duotrigintillion",
  102: "Tretrigintillion",
  105: "Quattuortrigintillion"
};

export default largeNumbers;